apiVersion: v1
kind: Secret
metadata:
  name: printfarm-secret
  namespace: printfarm
type: Opaque
stringData:
  POSTGRES_DB: app
  POSTGRES_USER: stemlab_app
  POSTGRES_PASSWORD: stemlab_password
  DATABASE_URL: postgresql://stemlab_app:stemlab_password@postgres:5432/app